trigger:
  branches:
    include:
    - master

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
  REPOSITORY_NAME: $(Build.Repository.Name)
  COMMIT_TAG: $(git log --format=%h -1)

steps:
- script: |
    curl -L https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -o pacman.deb
    sudo apt update
    sudo apt install p7zip-full haveged qrencode
    sudo dpkg -i pacman.deb
    sudo dkp-pacman -Sy
    sudo dkp-pacman -S 3ds-dev --noconfirm
    curl -L https://github.com/Steveice10/bannertool/releases/download/1.1.0/bannertool.zip -o bannertool.zip
    sudo 7z e bannertool.zip linux-x86_64/bannertool
    sudo chmod +x bannertool
    rm bannertool.zip
    curl -L https://github.com/profi200/Project_CTR/releases/download/0.15/makerom_015_ctrtool.zip -o makerom_015_ctrtool.zip
    sudo 7z e makerom_015_ctrtool.zip Linux_x86_64/makerom
    sudo chmod +x makerom
    rm makerom_015_ctrtool.zip
  displayName: 'Setup devkitPro'
  
- script: |
    export PATH=$PATH:$(pwd)
    export DEVKITPRO="/opt/devkitpro"
    export DEVKITARM="/opt/devkitpro/devkitARM"
    make
    cp Athena.3dsx $(Build.ArtifactStagingDirectory)
    cp Athena.cia $(Build.ArtifactStagingDirectory)
    echo '##vso[task.setvariable variable=COMMIT_TAG]'$(git log --format=%h -1)
    echo '##vso[task.setvariable variable=COMMIT_MESSAGE]'$(git log --pretty=format:"%an - %s" -1)
  displayName: 'Build Athena'

- script: |
    git config --global user.email "flamekat54@aol.com"
    git config --global user.name "TWLBot"
    git clone --depth 1 https://$GITHUB_TOKEN@github.com/Universal-Team/extras.git
    mkdir extras/builds/Athena/
    cd extras/builds/Athena/
    cp ../../../Athena.3dsx Athena.3dsx
    cp ../../../Athena.cia Athena.cia
    qrencode -o Athena.png https://github.com/Universal-Team/extras/releases/download/v$CURRENT_DATE/LeafEdit.cia
    git stage .
    git commit -m "Athena | $(COMMIT_TAG)"
    git push origin master
    git tag v$CURRENT_DATE
    echo '##vso[task.setvariable variable=TWLBOT_COMMIT]'$(git log -1 --format="%H")
  displayName: "Commit to Universal-Team/extras"

- task: GitHubRelease@0
  displayName: "Release to Universal-Team/extras"
  inputs:
    gitHubConnection: TWLBot
    repositoryName: Universal-Team/extras
    action: create
    target: $(TWLBOT_COMMIT)
    tagSource: 'manual'
    tag: v$(CURRENT_DATE)
    title: Athena | $(COMMIT_TAG)
    releaseNotesSource: input
    releaseNotes: $(COMMIT_MESSAGE)
    assets: '$(Build.ArtifactStagingDirectory)/*'
    isPreRelease: true
    addChangeLog: false

- script: |
    curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    export IMAGE=https://raw.githubusercontent.com/Universal-Team/extras/v$CURRENT_DATE/Universal-Manager/Athena.png
    ./send.sh success $WEBHOOK_URL
  condition: succeeded()
  displayName: "Send success webhook"
- script: |
    curl -o send.sh https://raw.githubusercontent.com/Universal-Team/discord-webhooks/master/send-azure.sh
    chmod +x send.sh
    ./send.sh failure $WEBHOOK_URL
  condition: failed()
  displayName: "Send failure webhook"
